package media

//go:generate go run ../codegen/main.go media media GetServiceCapabilities
//go:generate go run ../codegen/main.go media media GetVideoSources
//go:generate go run ../codegen/main.go media media GetAudioSources
//go:generate go run ../codegen/main.go media media GetAudioOutputs
//go:generate go run ../codegen/main.go media media CreateProfile
//go:generate go run ../codegen/main.go media media GetProfile
//go:generate go run ../codegen/main.go media media GetProfiles
//go:generate go run ../codegen/main.go media media AddVideoEncoderConfiguration
//go:generate go run ../codegen/main.go media media RemoveVideoEncoderConfiguration
//go:generate go run ../codegen/main.go media media AddVideoSourceConfiguration
//go:generate go run ../codegen/main.go media media RemoveVideoSourceConfiguration
//go:generate go run ../codegen/main.go media media AddAudioEncoderConfiguration
//go:generate go run ../codegen/main.go media media RemoveAudioEncoderConfiguration
//go:generate go run ../codegen/main.go media media AddAudioSourceConfiguration
//go:generate go run ../codegen/main.go media media RemoveAudioSourceConfiguration
//go:generate go run ../codegen/main.go media media AddPTZConfiguration
//go:generate go run ../codegen/main.go media media RemovePTZConfiguration
//go:generate go run ../codegen/main.go media media AddVideoAnalyticsConfiguration
//go:generate go run ../codegen/main.go media media RemoveVideoAnalyticsConfiguration
//go:generate go run ../codegen/main.go media media AddMetadataConfiguration
//go:generate go run ../codegen/main.go media media RemoveMetadataConfiguration
//go:generate go run ../codegen/main.go media media AddAudioOutputConfiguration
//go:generate go run ../codegen/main.go media media RemoveAudioOutputConfiguration
//go:generate go run ../codegen/main.go media media AddAudioDecoderConfiguration
//go:generate go run ../codegen/main.go media media RemoveAudioDecoderConfiguration
//go:generate go run ../codegen/main.go media media DeleteProfile
//go:generate go run ../codegen/main.go media media GetVideoSourceConfigurations
//go:generate go run ../codegen/main.go media media GetVideoEncoderConfigurations
//go:generate go run ../codegen/main.go media media GetAudioSourceConfigurations
//go:generate go run ../codegen/main.go media media GetAudioEncoderConfigurations
//go:generate go run ../codegen/main.go media media GetVideoAnalyticsConfigurations
//go:generate go run ../codegen/main.go media media GetMetadataConfigurations
//go:generate go run ../codegen/main.go media media GetAudioOutputConfigurations
//go:generate go run ../codegen/main.go media media GetAudioDecoderConfigurations
//go:generate go run ../codegen/main.go media media GetVideoSourceConfiguration
//go:generate go run ../codegen/main.go media media GetVideoEncoderConfiguration
//go:generate go run ../codegen/main.go media media GetAudioSourceConfiguration
//go:generate go run ../codegen/main.go media media GetAudioEncoderConfiguration
//go:generate go run ../codegen/main.go media media GetVideoAnalyticsConfiguration
//go:generate go run ../codegen/main.go media media GetMetadataConfiguration
//go:generate go run ../codegen/main.go media media GetAudioOutputConfiguration
//go:generate go run ../codegen/main.go media media GetAudioDecoderConfiguration
//go:generate go run ../codegen/main.go media media GetCompatibleVideoEncoderConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleVideoSourceConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleAudioEncoderConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleAudioSourceConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleVideoAnalyticsConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleMetadataConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleAudioOutputConfigurations
//go:generate go run ../codegen/main.go media media GetCompatibleAudioDecoderConfigurations
//go:generate go run ../codegen/main.go media media SetVideoSourceConfiguration
//go:generate go run ../codegen/main.go media media SetVideoEncoderConfiguration
//go:generate go run ../codegen/main.go media media SetAudioSourceConfiguration
//go:generate go run ../codegen/main.go media media SetAudioEncoderConfiguration
//go:generate go run ../codegen/main.go media media SetVideoAnalyticsConfiguration
//go:generate go run ../codegen/main.go media media SetMetadataConfiguration
//go:generate go run ../codegen/main.go media media SetAudioOutputConfiguration
//go:generate go run ../codegen/main.go media media SetAudioDecoderConfiguration
//go:generate go run ../codegen/main.go media media GetVideoSourceConfigurationOptions
//go:generate go run ../codegen/main.go media media GetVideoEncoderConfigurationOptions
//go:generate go run ../codegen/main.go media media GetAudioSourceConfigurationOptions
//go:generate go run ../codegen/main.go media media GetAudioEncoderConfigurationOptions
//go:generate go run ../codegen/main.go media media GetMetadataConfigurationOptions
//go:generate go run ../codegen/main.go media media GetAudioOutputConfigurationOptions
//go:generate go run ../codegen/main.go media media GetAudioDecoderConfigurationOptions
//go:generate go run ../codegen/main.go media media GetGuaranteedNumberOfVideoEncoderInstances
//go:generate go run ../codegen/main.go media media GetStreamUri
//go:generate go run ../codegen/main.go media media StartMulticastStreaming
//go:generate go run ../codegen/main.go media media StopMulticastStreaming
//go:generate go run ../codegen/main.go media media SetSynchronizationPoint
//go:generate go run ../codegen/main.go media media GetSnapshotUri
//go:generate go run ../codegen/main.go media media GetVideoSourceModes
//go:generate go run ../codegen/main.go media media SetVideoSourceMode
//go:generate go run ../codegen/main.go media media GetOSDs
//go:generate go run ../codegen/main.go media media GetOSD
//go:generate go run ../codegen/main.go media media GetOSDOptions
//go:generate go run ../codegen/main.go media media SetOSD
//go:generate go run ../codegen/main.go media media CreateOSD
//go:generate go run ../codegen/main.go media media DeleteOSD
